# Generated by Django 4.1.9 on 2023-06-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chef",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chef_name", models.CharField(max_length=100)),
                ("chef_desc", models.CharField(max_length=200)),
                ("chef_rest", models.CharField(max_length=100)),
                ("chef_practice", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-chef_practice"],
            },
        ),
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipe_name", models.CharField(max_length=100)),
                ("recipe_category", models.CharField(max_length=100)),
                ("recipe_type", models.CharField(max_length=100)),
                ("recipe_desc", models.CharField(max_length=200)),
                ("recipe_id", models.UUIDField()),
                ("recipe_slug", models.SlugField()),
                ("created_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_date"],
            },
        ),
    ]
