# Generated by Django 4.1.9 on 2023-06-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="recipe_id",
            field=models.UUIDField(auto_created=True),
        ),
    ]
