# Generated by Django 4.1.9 on 2023-06-03 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0002_alter_recipes_recipe_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="recipe_id",
            field=models.UUIDField(auto_created=True, null=True),
        ),
        migrations.AlterField(
            model_name="recipes",
            name="recipe_slug",
            field=models.SlugField(null=True),
        ),
    ]
