# Generated by Django 4.1.9 on 2023-06-03 12:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("crud", "0003_alter_recipes_recipe_id_alter_recipes_recipe_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipes",
            name="recipe_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
