# Generated by Django 4.1.9 on 2023-06-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Books",
            fields=[
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("desc", models.TextField()),
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
